### ISSUE TITLE
how to solve RecursionError with online_train.py

### ISSUE THREAD

**Issue by thunder95** [SimpleBerry/LLaMA-O1#23]
Id:0->1, Child: <problem>In the graph of $\frac{x^3-4x}{q(x)}*\frac{x^3+4x}{r(x)}$$,\ each $x$ such that $\sqrt{\frac{x^5-4x}{q^3x^2+4^3}\cdot, Policy: 1.0, Value: 0.5008712234296745
  0%|                                                                                                                                                                               | 0/16 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "/LLaMA-O1/online_train.py", line 1130, in <module>
    trainer.train(num_iterations=num_iterations)
  File "//LLaMA-O1/online_train.py", line 929, in train
    root_node = self.self_play(initial_state)
  File "/LLaMA-O1/online_train.py", line 798, in self_play
    root_node = self.mcts.search(root_node)
  File "/LLaMA-O1/online_train.py", line 274, in search
    self.simulate(root_node)
  File "LLaMA-O1/online_train.py", line 292, in simulate
    value = self.expand_node(node) * self.discount_factor
  File /LLaMA-O1/online_train.py", line 305, in expand_node
    state=text, parent=node, index=get_max_node_id_in_tree(node) + 1
  File "/LLaMA-O1/online_train.py", line 97, in get_max_node_id_in_tree
    max_id = max(max_id, get_max_node_id_in_tree(child))
  File "LLaMA-O1/online_train.py", line 97, in get_max_node_id_in_tree
    max_id = max(max_id, get_max_node_id_in_tree(child))
  File "/LLaMA-O1/online_train.py", line 97, in get_max_node_id_in_tree
    max_id = max(max_id, get_max_node_id_in_tree(child))
  [Previous line repeated 991 more times]
RecursionError: maximum recursion depth exceeded

**Comment by Presbyterate** [comment]
Same question

**Comment by thunder95** [comment]
There seems to be a dead loop, parent->child->parent->child..... I tried to solve it as follows,  not a correct way possibly.

 def get_max_node_id_in_tree(node, find_top=True):
    if find_top and node.parent:
        while node.parent:
            node = node.parent
    max_id = node.index
    #print(max_id, len(node.children))
    for child in node.children:
        #print(node, child, node==child, node.index, child.index)
        max_id = max(max_id, get_max_node_id_in_tree(child, False))
    return max_id

**Comment by Presbyterate** [comment]
ill have a try

**Comment by trotsky1997** [comment]
https://huggingface.co/SimpleBerry/LLaMA-O1-Supervised-1129
